In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("spam.csv")
df.head()

,Category,Message
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."


In [3]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [4]:
df['spam'] = df['Category'].apply(lambda x: 1 if x =='spam' else 0)

In [5]:
df.shape

(5572, 3)

In [6]:
df.head()

,Category,Message,spam
0,ham,"Go until jurong point, crazy.. Available only ...",0
1,ham,Ok lar... Joking wif u oni...,0
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,1
3,ham,U dun say so early hor... U c already then say...,0
4,ham,"Nah I don't think he goes to usf, he lives aro...",0


In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [8]:
X_train.shape

(4457,)

In [9]:
X_test.shape

(1115,)

In [10]:
type(X_train)

pandas.core.series.Series

In [11]:
X_train[:4]

5050    Edison has rightly said, "A fool can ask more ...
1174                            Ü dun need to pick ur gf?
2915    Sorry! U can not unsubscribe yet. THE MOB offe...
4424    alright. Thanks for the advice. Enjoy your nig...
Name: Message, dtype: object

In [12]:
type(y_train)

pandas.core.series.Series

In [13]:
y_train[:4]

5050    0
1174    0
2915    1
4424    0
Name: spam, dtype: int64

In [14]:
type(X_train.values)

numpy.ndarray

In [15]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59301 stored elements and shape (4457, 7798)>

In [16]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [17]:
X_train_cv.shape

(4457, 7798)

In [18]:
v.get_feature_names_out()[1771]

'cheetos'

In [19]:
v.vocabulary_

{'edison': 2543,
 'has': 3354,
 'rightly': 5817,
 'said': 5915,
 'fool': 2944,
 'can': 1632,
 'ask': 1099,
 'more': 4605,
 'questions': 5551,
 'than': 6845,
 'wise': 7585,
 'man': 4354,
 'answer': 985,
 'now': 4858,
 'you': 7760,
 'know': 3979,
 'why': 7550,
 'all': 912,
 'of': 4909,
 'us': 7262,
 'are': 1055,
 'speechless': 6400,
 'during': 2506,
 'viva': 7365,
 'gm': 3167,
 'gn': 3169,
 'ge': 3106,
 'gnt': 3171,
 'dun': 2500,
 'need': 4746,
 'to': 6983,
 'pick': 5222,
 'ur': 7250,
 'gf': 3137,
 'sorry': 6359,
 'not': 4844,
 'unsubscribe': 7227,
 'yet': 7746,
 'the': 6858,
 'mob': 4560,
 'offer': 4916,
 'package': 5063,
 'min': 4500,
 'term': 6816,
 '54': 550,
 'weeks': 7491,
 'pls': 5280,
 'resubmit': 5787,
 'request': 5756,
 'after': 850,
 'expiry': 2738,
 'reply': 5749,
 'themob': 6869,
 'help': 3412,
 'info': 3690,
 'alright': 925,
 'thanks': 6848,
 'for': 2952,
 'advice': 833,
 'enjoy': 2618,
 'your': 7766,
 'night': 4796,
 'out': 5028,
 'ma': 4306,
 'try': 7106,
 'get': 3127,
 '

In [20]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [23]:
np.where(X_train_np[0]!=0)

(array([ 912,  985, 1055, 1099, 1632, 2506, 2543, 2944, 3106, 3167, 3169,
        3171, 3354, 3979, 4354, 4605, 4858, 4909, 5551, 5817, 5915, 6400,
        6845, 7262, 7365, 7550, 7585, 7760]),)

In [25]:
X_train_np[0][1771]

np.int64(0)

In [26]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [27]:
X_test_cv = v.transform(X_test)

In [28]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       973
           1       0.97      0.96      0.97       142

    accuracy                           0.99      1115
   macro avg       0.98      0.98      0.98      1115
weighted avg       0.99      0.99      0.99      1115



In [29]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

In [30]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

In [31]:
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [32]:
y_pred = clf.predict(X_test)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00       973
           1       0.97      0.96      0.97       142

    accuracy                           0.99      1115
   macro avg       0.98      0.98      0.98      1115
weighted avg       0.99      0.99      0.99      1115

